# permissions for end users to edit gateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gateway-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gateway-operator
    app.kubernetes.io/part-of: gateway-operator
    app.kubernetes.io/managed-by: kustomize
  name: gateway-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - gateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - gateways/status
  verbs:
  - get
